[outputFormats.Search]
baseName = "index"
path = "search"
isHTML = true
mediaType = "text/html"
notAlternative = true

[outputFormats.SearchIndex]
baseName = "search"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params]
title_separator = "-"
title_sections = true
title_sections_depth = 0
title_sections_depth_dir = "end"

[params.hugopress]
debug = false

[params.search]
sass_transpiler = "dartsass"
modal_container = "body"
modal_toggle_selector = ".search-modal-toggle"
stall_threshold = 300
case_sensitive = false
min_match_char_length = 1
location = 0
threshold = 0.6
distance = 100
ignore_location = false
shortcut_close = ["Escape"]
shortcut_search = ["Control", "k"]
paginate = 20
index_all_pages = false
index_content = false
index_headings = true
index_summary = true
index_taxonomies = true
expand_results_meta = false
lazy_loading = true
filter_taxonomies = true
filter_years = true
histories = true
histories_count = 5
headings_end_level = 6

[params.search.key_weights]
title = 1
summary = 1
headings = 0.5
content = 0.5
lang = 1
year = 1
taxonomies = 0.1

[params.bootstrap.config_toggle]
langs = ["toml", "yaml", "json"]

[params.bootstrap.article_cards]
limit = 12
image_height = 240

[params.hugomods.images]
class_name = "img-fluid"
alignment_center_class_name = "d-block text-center"
alignment_start_class_name = "float-start me-2"
alignment_end_class_name = "float-end ms-2"
figure_class_name = "figure"
figure_caption_class_name = "figure-caption"
figure_image_class_name = "figure-img"
modern_format = "webp"

[params.emgithub]
endpoint = "https://emgithub.com/embed-v2.js"
branch = "main"
type = "markdown"
style = "default"
border = true
line_numbers = true
full_path = true
copy_button = true
file_meta = true
js_delivr = false

[params.seo.favicons]
icon = "favicon.png"
mask_icon = "mask-icon.svg"
mask_icon_color = "#000000"

[params.code_block_panel]
line_nos = true
max_lines = 10
wrap = false

[params.hb]
css_bundle_name = "hb"
js_bundle_name = "hb"
logo = "/images/logo.png"
color = "light"
sass_transpiler = "dartsass"

[params.hb.styles]
prefix = "hb-"
hb_top_offset = "24px"

[params.hb.tables]
align = ""
bordered = true
border_style = ""
group_divider = false
hover = true
striped = true
striped_columns = false
style = ""
thead_style = ""

[params.hb.blockquotes]
bordered = true
border_width = 4
border_style = "primary"

[params.hb.header]
breakpoint = "lg"
sticky = true
full_width = true

[params.hb.announcement_bar]
interval = 5000
expand_stall_threshold = 1000

[params.hb.back_to_top]
icon_height = "2em"
icon_width = "2em"
icon_name = "rocket"
position_bottom = "1rem"
position_end = "1rem"
animation = true

[params.hb.progress_bar]
height = "2px"
initial_width = 20
interval = 50
time = 2

[params.hb.breadcrumb]
disabled = false

[params.hb.content_panel]
bottom = "20px"
comments = true

[params.hb.heading_sign]
symbol = "§"

[params.hb.heading_sign.containers.".hb-blog-post-content"]

[params.hb.heading_sign.containers.".hb-docs-doc-content"]

[params.hb.pagination]
alignment = "center"
size = ""
siblings = 2

[params.hb.toc_scrollspy]
border = true

[params.hb.search]
modal = true

[params.hb.terms]
paginate = 12
profile = true
profile_metrics = true
list_style = ""

[params.hb.blog]
list_style = ""
list_pinned_posts = 1
full_width = false
paginate = 12
post_date_format = ":date_long"
post_thumbnail = true
post_thumbnail_height = "160px"
post_thumbnail_placeholder = ""
post_thumbnail_default = "images/thumbnail.png"
post_thumbnail_position = "top"
post_thumbnail_resize_height = 360
list_cols_md = 2
list_cols_lg = 3

[params.hb.blog.archives]
paginate = 30

[params.hb.blog.home]
pinned_posts_position = ""

[params.hb.blog.sidebar]
position = "start"
width = 0.35
max_width = "320px"
sticky = true

[params.hb.blog.toc]
position = "end"

[params.hb.blog.related_posts]
number = 10

[params.hb.blog.social_share_buttons]
media = []

[params.hb.docs]
date_format = ":date_long"
navs_reduce_font_size = false
navs_sticky_scroll = true
navs_active_style = ""

[params.hb.docs.social_share_buttons]
media = []

[params.hb.full_width_types.docs]
enable = true

[params.hb.modules.code-block-panel]

[[params.hb.modules.code-block-panel.js_resources]]
partial = "code-block-panel/assets/js-resource"

[params.hugopress.modules.hb.attributes.document]
cacheable = true

[params.hugopress.modules.hb.attributes.body]

[params.hugopress.modules.hb.attributes.hb-main]

[params.hugopress.modules.hb.attributes.hb-alias-refresh-meta]

[params.hugopress.modules.hb.hooks.head-begin]
cacheable = true

[params.hugopress.modules.hb.hooks.head-end]
cacheable = true

[params.hugopress.modules.hb.hooks.body-end]
cacheable = true
weight = 1000

[params.hugopress.modules.hb-announcement-bar.hooks.hb-header-nav-before]
cacheable = true
weight = 1

[params.hugopress.modules.hb-base.hooks.hb-body-begin]
cacheable = false
partial = "hb/modules/header/index"

[params.hugopress.modules.hb-base.hooks.hb-body-end]
weight = 1
cacheable = true
partial = "hb/modules/footer/index"

[params.hugopress.modules.hb-blog.hooks.head-begin]
cacheable = true
cache_param_key = "external_url"

[params.hugopress.modules.hb-blog-breadcrumb.hooks.hb-blog-main-begin]
weight = 1

[params.hugopress.modules.hb-blog-post-content-panel.hooks.hb-blog-post-content-end]

[params.hugopress.modules.hb-blog-post-nav.hooks.hb-blog-post-content-end]

[params.hugopress.modules.hb-blog-related-posts.hooks.hb-blog-post-content-end]

[params.hugopress.modules.hb-blog-comments-disqus.hooks.hb-blog-post-comments]

[params.hugopress.modules.hb-blog-social-share-buttons.hooks.hb-blog-post-content-end]
weight = 1

[params.hugopress.modules.hb-blog-toc-scrollspy.attributes.hb-blog-post-content]
cacheable = true

[params.hugopress.modules.hb-docs.hooks.head-begin]
cacheable = true
cache_param_key = "redirect"

[params.hugopress.modules.hb-docs.hooks.hb-header-nav-begin]
cacheable = true
cache_key = "page.Type"

[params.hugopress.modules.hb-docs-breadcrumb.hooks.hb-docs-main-begin]
weight = 1

[params.hugopress.modules.hb-docs-doc-content-panel.hooks.hb-docs-doc-content-end]

[params.hugopress.modules.hb-docs-doc-nav.hooks.hb-docs-doc-content-end]

[params.hugopress.modules.hb-docs-comments-disqus.hooks.hb-docs-doc-comments]

[params.hugopress.modules.hb-docs-social-share-buttons.hooks.hb-docs-doc-content-end]
weight = 1

[params.hugopress.modules.hb-docs-toc-scrollspy.attributes.hb-docs-doc-content]
cacheable = true

[params.hugopress.modules.hb-footer-socials.hooks.hb-footer-site-info-end]
weight = 1
cacheable = true

[params.hugopress.modules.hb-header-search.hooks.hb-header-togglers-begin]
cacheable = true
partial = "hb/modules/header-search/index"

[params.hugopress.modules.hb-header-socials.hooks.hb-header-panel]
weight = 1
cacheable = true

[params.hugopress.modules.hb-noscript.hooks.body-begin]
weight = 1
cacheable = true

[params.hugopress.modules.search.hooks.head-end]
disabled = true

[params.hugopress.modules.search.hooks.body-end]
disabled = true

[params.hugopress.modules.hb-search.hooks.head-end]
cacheable = true

[params.hugopress.modules.hb-search.hooks.body-end]
cacheable = true
cache_site_param_key = "hb.search.modal"

[params.hugopress.modules.seo-alternatives.hooks.head-begin]
partial = "seo/modules/alternatives/index"

[params.hugopress.modules.seo-base.attributes.document]
cacheable = true

[params.hugopress.modules.seo-base.hooks.head-begin]
partial = "seo/modules/base/index"

[params.hugopress.modules.seo-favicons.hooks.head-begin]
cacheable = true
partial = "seo/modules/favicons/index"

[params.hugopress.modules.seo-open-graph.hooks.head-begin]
partial = "seo/modules/open-graph/index"

[params.hugopress.modules.seo-schema.attributes.document]
cacheable = true

[params.hugopress.modules.seo-schema.hooks.head-begin]
partial = "seo/modules/schema/index"

[params.hugopress.modules.seo-twitter-cards.hooks.head-begin]
partial = "seo/modules/twitter-cards/index"
